name: signal_example_flutter
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  libsignal_protocol_dart:
    path: packages/libsignal_protocol_dart

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
