name: signal_example_flutter
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path_provider: ^2.0.2
  libsignal_protocol_dart:
    path: packages/libsignal_protocol_dart
  socket_io_client: ^2.0.0-beta.2
  # adhara_socket_io: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

